### ISSUE TITLE
show something better when player gets one on a dice, currently i am using alert box

### ISSUE THREAD

**Issue by hardikhere** [hardikhere/piggame.github.io#1]

**Comment by RaunaqChawhan** [comment]
I would like to work on it

**Comment by hardikhere** [comment]
> I would like to work on it

go ahead

**Comment by hardikhere** [comment]
> I would like to work on it

clone it again please

**Comment by RaunaqChawhan** [comment]
Yeah, I'll do changes on a new branch and send in a pull request
